# -*- coding: utf-8 -*-
"""Abdelrahman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mal_S6OHPvUEugZ1lKLYyZqV8dtkUc9w
"""

import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25.0, 27.6, 30.0, 29.6, 28.0],
    'City': ['Cairo', 'Paris', 'Paris', 'London', 'Paris'],
    'Math Score': [90, 75, 85, 70, 88],
    'Science Score': [95, 65, 82, 60, 91]
}
df = pd.DataFrame(data)

df['Math Score']

df[df['Science Score'] > 80]

df['Average']=(df['Science Score']+df['Math Score'])/2
df

df.sort_values('Average', ascending=True)

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, np.nan, 30, np.nan, 28],
    'City': ['Cairo', 'Paris', None, 'London', 'Paris'],
    'Salary': [5000, 6000, None, 5500, 5800]
}
df2=pd.DataFrame(data)
df2

df2.isnull().sum()

df2['Age']=df2['Age'].fillna(df['Age'].mean())
df2

df2['City']=df2['City'].fillna('Unknown')
df2

df2=df2.dropna(subset=['Salary'])
df2