# -*- coding: utf-8 -*-
"""pandas task azab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XerAW3ZRNxK02KkAXp4xx2B-1SsdgeTL

# Task 1: Basic DataFrame Operations
Create a DataFrame with student data:

Name, Age, City, Math Score, Science Score

Select only the Math Score column.

Filter students who scored above 80 in Science.

Add a new column Average Score as the mean of Math & Science.

Sort students by Average Score descending.
"""

import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 27, 30, 35, 28],
    'City': ['Cairo', 'Paris', "Paris", 'London', 'Paris'],
    'Math Score': [100, 60, 67, 85, 98],
    'Science Score': [82, 60, 63, 45, 28]
}

df = pd.DataFrame(data)
df

df['Math Score']

df[df['Science Score'] > 80]

df['avg'] = (df['Science Score'] + df['Math Score']) / 2

df

df.sort_values('avg', ascending=False)

"""# Task 2: Missing Data
You are given this dataset:


data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, np.nan, 30, np.nan, 28],
    'City': ['Cairo', 'Paris', None, 'London', 'Paris'],
    'Salary': [5000, 6000, None, 5500, 5800]
}


Find how many missing values are in each column.

Fill missing Age with the average Age.

Fill missing City with "Unknown".

Drop any rows where Salary is missing.

"""

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, np.nan, 30, np.nan, 28],
    'City': ['Cairo', 'Paris', None, 'London', 'Paris'],
    'Salary': [5000, 6000, None, 5500, 5800]
}
df2 = pd.DataFrame(data)

df2

df2.isna().sum()

df2['Age'].mean()

df2['Age'] = df2['Age'].fillna(df2['Age'].mean())

df2['Age'] = df2['Age'].apply(lambda x: round(x))

df2

df2['City'] = df2['City'].fillna('Unknown')

df2

df2 = df2.dropna(subset=['Salary'])

df2

df2 = df2.reset_index(drop=True)

df2