# -*- coding: utf-8 -*-
"""folium.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YAotAi9G8tYW3SmTaPHVHbtCAOgkeICx
"""

import folium

latitude = 31.24078356993472
longitude = 29.96322756919405

m = folium.Map(location=[latitude, longitude], zoom_start=13)

icon_url ='human-left-hand-finger-pointing-down-image-png-704081695136680a6b5ykrmx2.png'
icon = folium.CustomIcon(
    icon_url,
    icon_size=(38, 95),
    icon_anchor=(22, 94),
)

folium.Marker(
    location=[latitude, longitude],
    popup=folium.Popup("Royal Jewelry Museum", max_width=250),
    tooltip="Click for more",
    icon=icon
).add_to(m)

m

from google.colab import files
uploaded = files.upload()